apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: site-instance
spec:
  catalogType: instance
  properties:
    spec: 
      solution: site-app
      target:
        selector:
          group: site